version: '3.1'

services:
  
  calculator:
    build: .
   
  redis:
    image: redis:alpine
  
  user-service:
    image: webdevtoolsandtech/user-service
    environment:
      REDIS_ADDRESS: redis:6379
    depends_on:
      - redis

  currency-frontend:
    image: webdevtoolsandtech/currency-frontend
    
  currency-backend:
    image: webdevtoolsandtech/currency-backend
    ports: 
      - "3000:80"
    environment:
      REDIS_ADDRESS: redis:6379
      SESSION_SECRET: 'ayeletriki'
      USER_SERVICE_ADDRESS: user-service:80
      FRONTEND_ADDRESS: currency-frontend:80
      CALCULATOR_ADDRESS: calculator:3000
    depends_on:
      - redis
      - calculator
      - user-service
